# Generated by Django 5.1.7 on 2025-03-13 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ELECTRICAL', 'Electrical'), ('MECHANICAL', 'Mechanical')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('reported_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolution_timestamp', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.area')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.issuetype')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.shift')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ELECTRICAL', 'Electrical'), ('MECHANICAL', 'Mechanical')], max_length=20)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'Under Progress'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('planned_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.area')),
            ],
        ),
    ]
