# Generated by Django 5.1.7 on 2025-03-13 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RakeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rake_id', models.CharField(help_text='Unique identifier for the rake', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'Under Progress'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reported_by', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.area')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.material')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.shift')),
            ],
        ),
        migrations.CreateModel(
            name='RakeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'Under Progress'), ('PENDING', 'Pending')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('rake_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rake_handling.rakeentry')),
            ],
        ),
    ]
