# Generated by Django 5.1.6 on 2025-03-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_material_options_alter_material_type'),
        ('rake_handling', '0002_rakeentry_wagon_tippler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rakeentry',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rake_entries', to='operations.area'),
        ),
        migrations.AlterField(
            model_name='rakeentry',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rakeentry',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rake_entries', to='operations.material'),
        ),
        migrations.AlterField(
            model_name='rakeentry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rakeentry',
            name='rake_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rakeentry',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rake_entries', to='operations.shift'),
        ),
        migrations.AlterField(
            model_name='rakeentry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='rakeentry',
            name='wagon_tippler',
            field=models.CharField(choices=[('WT1', 'Wagon Tippler 1'), ('WT2', 'Wagon Tippler 2'), ('WT3', 'Wagon Tippler 3'), ('WT4', 'Wagon Tippler 4')], default='WT1', max_length=10),
        ),
        migrations.AlterField(
            model_name='rakenotification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=20),
        ),
    ]
