# Generated by Django 5.1.6 on 2025-03-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rake_handling', '0003_alter_rakeentry_area_alter_rakeentry_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rakeentry',
            name='wagon_tippler',
            field=models.CharField(choices=[('WT-1', 'Wagon Tippler 1'), ('WT-2', 'Wagon Tippler 2'), ('WT-3', 'Wagon Tippler 3'), ('WT-4', 'Wagon Tippler 4')], default='WT-1', max_length=10),
        ),
    ]
