# Generated by Django 5.1.7 on 2025-03-15 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rake_handling', '0005_remove_area_shift_fields'),
    ]

    operations = [
    ]
