# Generated by Django 5.1.7 on 2025-03-13 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_feeding', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_reclaiming', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_crushing', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_receiving', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.area')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Shift A (6:00 AM - 2:00 PM)'), ('B', 'Shift B (2:00 PM - 10:00 PM)'), ('C', 'Shift C (10:00 PM - 6:00 AM)')], max_length=1)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Reclaiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(help_text='Source of reclaimed material', max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.area')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.material')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(help_text='Source of received material', max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.area')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.material')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('destination', models.CharField(help_text='Destination (e.g., process department, yard, bunker)', max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.area')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.material')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crushing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('initial_size', models.CharField(blank=True, help_text='Initial size before crushing', max_length=50, null=True)),
                ('final_size', models.CharField(blank=True, help_text='Final size after crushing', max_length=50, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.area')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.material')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
